import type { Metadata } from "next";
import { Inter } from "next/font/google";
import logo from "../img/logo-branca.png"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cybox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href='../img/logo-branca.png' type="image/x-icon" />
      </head>
      <body className={`${inter.className} flex flex-col h-screen scrollbar-thin scrollbar-thumb-yellow-700`}>

        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
